### ISSUE TITLE
Doesn't work with LICENSE.md

### ISSUE THREAD

**Issue by fharper** [FantasticFiasco/action-update-license-year#111]
The action only detect `LICENSE` file, not `LICENSE.md` one

**Comment by FantasticFiasco** [comment]
You're correct!

I'm currently in the process of finalizing v2 that will cover the use-cases described in #43. I think yours is among them, am I correct?

**Comment by fharper** [comment]
Oops, my bad, I should have read the open bugs! Looking forward for v2 for 2022 :)
