### ISSUE TITLE
Do we need to fetch the complete git history?

### ISSUE THREAD

**Issue by chances** [FantasticFiasco/action-update-license-year#120]
**Describe the bug**
Checking out existing branch fails in my CI workflow.

**To Reproduce**
My workflow file: https://github.com/chances/descartes-d/actions/runs/477666176/workflow

Failing CI build: https://github.com/chances/descartes-d/pull/2/checks?check_run_id=1681534009

**Expected behavior**
Your license year task is skipped because the `license/2021` branch already exists with license updates.

**Screenshots**
N/A

**Additional context**
Failing CI build: https://github.com/chances/descartes-d/pull/2/checks?check_run_id=1681534009

**Comment by FantasticFiasco** [comment]
Hi @chances!

I think replacing

```yaml
- uses: actions/checkout@v2
```

with

```yaml
- uses: actions/checkout@v2
  with:
    fetch-depth: 0
```

should fix your problem. Can you try it out and report back?

**Comment by chances** [comment]
@FantasticFiasco Hm, that seems to resolve it.

Why is `fetch-depth: 0` required?

**Comment by FantasticFiasco** [comment]
It seems that `actions/checkout@v2`, due to an optimization, only gets the lates commit by default. That operation will not get the tags, nor the branches of the repository. I can understand their decision, because most often in CI you only get the files to run the tests or what not, but we need more of the repo, and its history, thus the necessity to set `fetch-depth: 0`.

You can read more about their reasoning [here](https://github.com/actions/checkout/issues/217).

Please consider giving this repo a star if you find it beneficial. Currently stars are the only way to indicate usage for GitHub Actions. Thanks!

**Comment by chances** [comment]
Other GitHub actions that play with Git don't require this flag on the checkout action, e.g. `crazy-max/ghaction-github-pages@v2`.

Can your action not workaround it like these other actions?

**Comment by FantasticFiasco** [comment]
`crazy-max/ghaction-github-pages@v2` and this action doesn't share the same behaviour, thus you cannot compare them.

Where we in this action run git operations on the same repository checked out by the preceding `actions/checkout@v2`, `crazy-max/ghaction-github-pages@v2` doesn't. They clone the specific branch of the target repository into a temp directory, and doesn't do any changes at all in the source repository that was checked out by their preceding `actions/checkout@v2`.

I'm quite sure that you could have found that out by comparing the source code in this repo with the source code in their repo. So let me turn the table. If removing `fetch-depth: 0` is important to you, I challenge you to find a solution where we don't have to specify it using this action, and still remain with the same functionality.

**Comment by chances** [comment]
I'm well aware of the actions' differing behavior. My intention in bringing up the `crazy-max/ghaction-github-pages` action was with regard to its implicit recognition of the fetch depth optimization.

The `fetch-depth` requirement your action imposes wastes CI resources. The optimization is important, especially for large repos with heavy branch churn.

Your action could, instead of expecting the _entire_ history of the target repo, `git fetch` the branch refs of interest.

**Comment by FantasticFiasco** [comment]
You are correct, the change would be for a better one. One could play around with fetch depth, one could also remove the dependency towards `actions/checkout@v2` altogether and clone the repo ourselves. 

I'll leave the issue open. Let's see if it gets some traction.

**Comment by FantasticFiasco** [comment]
I've come to the conclusion that depending on composability, where we depend on `actions/checkout@v3`, isn't a bad thing.

Closing issue.
