### ISSUE TITLE
Release for security update from `tmpl`

### ISSUE THREAD

**Issue by aifrak** [FantasticFiasco/action-update-license-year#210]
Hello,

Someone recently opened an [issue on my repo](https://github.com/aifrak/dotfiles/issues/96) regarding your security update related to `tmpl`.

Since this security update was done after the `v2.1.0`, I currently am pointing to this commit sha instead of using `master`, `v2` or `v2.1.0`.

Would it be fine for you to cut a release in order to include the commit [0dd479f24c62cdbbbce52c7f2ee4277c778cae06](https://github.com/FantasticFiasco/action-update-license-year/commits/0dd479f24c62cdbbbce52c7f2ee4277c778cae06)?

**Comment by FantasticFiasco** [comment]
Hi @aifrak!

I'm dogfooding this action in my own repositories as well, and yesterday received issues of the same nature. I can assure you that the security issues relating to this codebase has only affected the dev dependencies, not the dependencies downloaded when the action is running in a workflow, but nevertheless I will create a new release in the upcoming days.

Thanks for notifying me regarding this issue.

**Comment by FantasticFiasco** [comment]
There's a new release available, and the git tag `v2` has been updated to reflect that as well.

Thanks for reporting the issue!
