### ISSUE TITLE
Signed Commits

### ISSUE THREAD

**Issue by C0D3-M4513R** [FantasticFiasco/action-update-license-year#217]
**Is your feature request related to a problem? Please describe.**
I recently [got a pull request in a repo of mine](https://github.com/C0D3-M4513R/AHKScripts/pull/11), to update the Year in the license as expected.
My issue with that PR was with two things:

1. My Linter Action for PRs just never completed?
2. The Commit to the PR was unsigned. I require signed commits though.

**Describe the solution you'd like**
Add a way, for this github-action to make signed commits.

**Describe alternatives you've considered**
Not requiring commit signing? idk?

 https://github.com/FantasticFiasco/action-update-license-year/issues/119#issuecomment-757544256 :
> because it would most probably require you to save your private key in GitHub

As a file, or in a config publicly (since workflows cannot use secrets)? - If yes, than this should NEVER be realeased as a feature. Public repos should NEVER have private gpg keys publicly accessible and private repos shouldn't have a need for Licences and signed commits.

**Comment by FantasticFiasco** [comment]
Hi @C0D3-M4513R and welcome to the repo!

Regarding the linter, I looked at your repo and especially the linter workflow, and found that this action isn't used in that workflow, thus I don't think they have anything in common. The problem with the linter is probably unrelated with this action.

Regarding signed commits, I will start to investigate it. To ease your mind, it would of course not involve publicly accessible secrets, but instead rely on GitHub Secrets, configured on the repo or organization. These secrets are available on branches and pull requests opened from the same repo, but will not be available on pull requests opened from forks.

**Comment by FantasticFiasco** [comment]
A heads up regarding the progress. The implementation is done, tests and documentation remains.

**Comment by FantasticFiasco** [comment]
The feature has now been released and you've been added to the list of contributors in `README.md`.

Thanks for the feature request!

**Comment by C0D3-M4513R** [comment]
I saw, that I've been added. Thank you, for making this action.
