### ISSUE TITLE
How to avoid pull request with multiple authors?

### ISSUE THREAD

**Issue by mondeja** [FantasticFiasco/action-update-license-year#308]
**Is your feature request related to a problem? Please describe.**

When I use this action setting as input the minimal input `with.repo: ${{ secrets.GITHUB_TOKEN }}`, the created PR is authored by two users, in the next case `41898282+github-actions[bot]@users.noreply.github.com` and `github-actions@github.com`:

![image](https://user-images.githubusercontent.com/23049315/210401395-c931c661-7896-4300-a00f-fb26ca79eba6.png)

**Describe the solution you'd like**

As the default author is `github-actions` and the default email is `github-actions@github.com` I would expect that only this user would be the author of the PR.

**Describe alternatives you've considered**

N/a

**Additional context**

N/a

**Comment by FantasticFiasco** [comment]
Hi @mondeja! I haven't payed attention if this is something new or it always was like this. I'm in the progress of releasing a new minor version, will look at this at the same time.

**Comment by FantasticFiasco** [comment]
Is your repository public? I would like to see the workflow file and the action logs.

**Comment by mondeja** [comment]
Yes, [workflow file](https://github.com/mondeja/mkdocs-include-markdown-plugin/blob/3ad7b27d1c2607dbacca91bab5074973bd78bfbc/.github/workflows/update-copyright-years.yml) and [action logs](https://github.com/mondeja/mkdocs-include-markdown-plugin/actions/runs/3819953003/jobs/6497909545).

**Comment by FantasticFiasco** [comment]
I've retried to reproduce your issue but somehow fail.

<img width="499" alt="image" src="https://user-images.githubusercontent.com/8513095/214428350-2a759180-4f5f-4a0d-bd17-a665bc750af6.png">

The PR title in this case is *Temp*.

I'm unsure on how to proceed, would you be able to provide steps that would reproduce the issue?

**Comment by FantasticFiasco** [comment]
Close due to inactivity
