### ISSUE TITLE
Configurable pull request

### ISSUE THREAD

**Issue by FantasticFiasco** [FantasticFiasco/action-update-license-year#57]
It may be desired to configure pull request related properties, e.g.:

- `branchName` - Might have to contain a variable for current year
- `commitMessage` - The message of the commit
- `commitBody` - The body of the commit
- `prTitle` - Pull request title
- `prBody` - Pull request body
- `assignees` - Pull request assignees
- `labels` - Pull request labels

**Comment by tenshiAMD** [comment]
@FantasticFiasco you may want to add to those something like the configuration below:

- `paths` - Repository paths for the LICENSE files (default: ./LICENSE)
-  `prDescription` - Pull request description (Note: Since I require PR description via mergeable)

**Comment by FantasticFiasco** [comment]
@tenshiAMD I'll add `prDescription` to the list and leave `paths` for #43.

I haven't heard about mergeable, is it [this one](https://github.com/mergeability/mergeable)?

**Comment by tenshiAMD** [comment]
@FantasticFiasco yeah that's the one I'm talking about

**Comment by FantasticFiasco** [comment]
This functionality is now released. A scenario in `README.md` highlights the changes.

Please get back to me if there is anything regarding PR configuration you would like.

**Comment by tenshiAMD** [comment]
@FantasticFiasco thanks a lot 👍
