### ISSUE TITLE
Validate indicated copyright year

### ISSUE THREAD

**Issue by tenshiAMD** [FantasticFiasco/action-update-license-year#59]
**Describe the bug**
I've setup the configuration as the documentation told so but when I've looked at the changes I saw redundant year range (2020-2020).

**To Reproduce**
Trigger action manually via workflow dispatch as soon as I've pushed my changes in the repo.

**Expected behavior**
It should not create pull request with redundant year range like 2020-2020.

**Additional context**
Please see the pull request created in my [repo](https://github.com/tenshiAMD/dev_box/pull/2/files)

**Comment by tenshiAMD** [comment]
@FantasticFiasco hi there, great action workflow you've got here, I was thinking if you have some time to fix this bug that will be awesome, thanks a lot In advance~!

**Comment by FantasticFiasco** [comment]
Yeah, this was pretty embarrassing 😞 I'll get right on to fixing the issue. Thanks for bringing it to my attention.

**Comment by FantasticFiasco** [comment]
The issue is fixed and part of the newest release. You'll need to close the existing pull request and trigger the workflow again, since the action isn't fixing already created pull requests.

Please let me know of it now works as expected. Thanks!

**Comment by tenshiAMD** [comment]
@FantasticFiasco indeed it is fixed now, thanks for the quick fix 👍

**Comment by tenshiAMD** [comment]
@all-contributors please add @tenshiAMD for bug

**Comment by tenshiAMD** [comment]
@FantasticFiasco hi, can I be included in the contributors list for bug reports?

**Comment by FantasticFiasco** [comment]
@tenshiAMD, I'm really sorry, of course you should be added to the list of contrubutors!
